/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_mobileqq_persistence_FTSDatatbaseDao */

#ifndef _Included_com_tencent_mobileqq_persistence_FTSDatatbaseDao
#define _Included_com_tencent_mobileqq_persistence_FTSDatatbaseDao
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_mobileqq_persistence_FTSDatatbaseDao
 * Method:    initFTS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tencent_mobileqq_persistence_FTSDatatbaseDao_initFTS
  (JNIEnv *, jobject);

/*
 * Class:     com_tencent_mobileqq_persistence_FTSDatatbaseDao
 * Method:    insertFTS
 * Signature: (JIJJLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_mobileqq_persistence_FTSDatatbaseDao_insertFTS
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jstring, jstring);

/*
 * Class:     com_tencent_mobileqq_persistence_FTSDatatbaseDao
 * Method:    queryFTSGroups
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_tencent_mobileqq_persistence_FTSDatatbaseDao_queryFTSGroups
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tencent_mobileqq_persistence_FTSDatatbaseDao
 * Method:    queryFTSMsgs
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_tencent_mobileqq_persistence_FTSDatatbaseDao_queryFTSMsgs
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tencent_mobileqq_persistence_FTSDatatbaseDao
 * Method:    closeFTS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tencent_mobileqq_persistence_FTSDatatbaseDao_closeFTS
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
